### ISSUE TITLE
ChatGPT-3.5-Turbo: Conversation data not being saved

### ISSUE THREAD

**Issue by InstaZDLL** [obiscr/ChatGPTGold#8]
### Discussed in https://github.com/obiscr/ChatGPTGold/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **InstaZDLL** May 15, 2023</sup>
I have a question, is it normal that **my conversations** in the **ChatGPT-3.5-Turbo** menu **are not saved** when I **refresh** or when I close and **re-open** my IDE?</div>

### The error in question :
The problem is that the **conversations** in the **menu ChatGPT-3.5-Turbo** are **not saved**, even if I create a **new conversation** that I **write** something like hey and I return to the **old conversation** all **disappear**, same when I **update** with the **button**.

#### Info : I'm using the trial version :
![Screenshot 2023-05-15 195358](https://github.com/obiscr/ChatGPTGold/assets/72951793/3726eb1a-aced-40db-9118-dd44b6b47e86)

![Animation3](https://github.com/obiscr/ChatGPTGold/assets/72951793/7df9a276-4465-4d5b-8055-4a7c93d149b8)

**Comment by obiscr** [comment]
I am working normally here and cannot reproduce this issue. Can you provide me with the relevant error logs?

First, have a conversation on GPT-3.5-Turbo, and then check Pycharm's idea.log to see if there are any related error logs.

This is my log file location (for reference only): C:\Users\obiscr\AppData\Local\JetBrains\PyCharm2023.1\log

**Comment by InstaZDLL** [comment]
I don't have an error in the PyCharm log file, I don't know why I have this error, maybe it's because I'm using PyCharm on **multiple devices** and the trial version is only active on **the first device** where I activated it.

I'll wait until the end of my trial period and buy a license to see if I still get the error.

**Comment by InstaZDLL** [comment]
Deprecated plugin

**Comment by obiscr** [comment]
Hi, please see https://github.com/obiscr/ChatGPTGold/issues/9#issuecomment-1605810851
