### ISSUE TITLE
End of life for gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by InstaZDLL** [obiscr/ChatGPTGold#9]
gpt-3.5-turbo-0613 has been released and now there is version gpt-3.5-turbo-16k can you add these two versions and delete the old gpt-5.5-turbo-0301?

### Old :
- gpt-3.5-turbo-0301

### New :
- gpt-3.5-turbo-0613
- gpt-3.5-turbo-16k
- gpt-3.5-turbo-16k-0613

https://platform.openai.com/docs/models/gpt-3-5

**Comment by InstaZDLL** [comment]
deprecated plugin

**Comment by obiscr** [comment]
Yes, please use the [ChatGPT ](https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode) plugin instead. ChatGPT plugin is now supported Conversation Manager and other major features. ChatGPTGold is marked as deprecated. **And it free to use**.
